name: Continous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  master:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout [master]
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - run: npm ci
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx-cloud record -- nx format:check
      - run: npx nx affected -t build lint test e2e
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request_target.head.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - run: npm ci
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx-cloud record -- nx format:check
      - run: npx nx affected -t build lint test e2e
